Update

diff --git a/shell/profile b/shell/profile
--- a/shell/profile
+++ b/shell/profile
@@ -23,48 +23,53 @@ if [ -d "$HOME/bin" ] ; then
     PATH="$HOME/bin:$PATH"
 fi
 
+# Homebrew
+export BREW_DIR="$HOME/.linuxbrew"
+export PATH="$BREW_DIR/bin:$PATH"
+export LD_LIBRARY="$BREW_DIR/lib:$LD_LIBRARY_PATH"
+
 # Set JAVA_HOME
-export JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64"
+export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
 #export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
 
 #THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
 export GVM_HOME="$HOME/.gvm"
 [[ -s "$GVM_HOME/bin/gvm-init.sh" ]] && source "$GVM_HOME/bin/gvm-init.sh"
 
-# Load RVM into a shell session *as a function*
+# Ruby versions manager
 export RVM_HOME="$HOME/.rvm"
 [[ -s "$RVM_HOME/scripts/rvm" ]] && source "$RVM_HOME/scripts/rvm"
 
-# This loads nvm
-export NVM_NODEJS_OGR_MIRROR=http://nodejs.org/dist
-export NVM_HOME="$HOME/.nvm"
-[ -s "$NVM_HOME/nvm.sh" ] && . "$NVM_HOME/nvm.sh"
+# Nodejs versions manager
+export NVM_NODEJS_ORG_MIRROR=http://nodejs.org/dist/
+export NVM_DIR=$HOME/.nvm
+source $(brew --prefix nvm)/nvm.sh
 
 # Autojump
 [[ -s "$HOME/.autojump/etc/profile.d/autojump.sh" ]] && source "$HOME/.autojump/etc/profile.d/autojump.sh"
 
-# Pythen version manager
+# Python versions manager
 export PYENV_ROOT="$HOME/.pyenv"
 export PATH="$PYENV_ROOT/bin:$PATH"
 eval "$(pyenv init -)"
 
-export NVM_DIR=~/.nvm
-source $(brew --prefix nvm)/nvm.sh
-
+# Mac Applications
 export DOXYGEN="/Applications/Doxygen.app/Contents/Resources"
 export APM_DIR="/Applications/Atom.app/Contents/Resources/app/apm"
 
-# Homebrew
-export PATH="$HOME/.linuxbrew/bin:$PATH"
-export LD_LIBRARY="$HOME/.linuxbrew/lib:$LD_LIBRARY_PATH"
+# Golang
+export GOPATH="$HOME/go"
+export GOROOT="$BREW_DIR/Cellar/go/1.5.1"
 
-export PATH=$JAVA_HOME/bin:$DOXYGEN:/opt/local/bin:/opt/local/sbin:$PATH
+export PATH=$GOROOT/bin:$JAVA_HOME/bin:$DOXYGEN:/opt/local/bin:/opt/local/sbin:$PATH
 
-echo
-echo "=============== Quote Of The Day ==============="
-echo
-fortune
-echo
-echo "================================================"
-echo
+#echo
+#echo "=============== Quote Of The Day ==============="
+#echo
+#fortune
+#echo
+#echo "================================================"
+#echo
+
+[[ -s "$HOME/dotfiles/resolv.conf" ]] && sudo ln -s $HOME/dotfiles/resolv.conf /etc/resolv.conf || echo "Resolv Fail"
 
